#!/usr/bin/env node
// Run once: node scripts/inline-fonts.js
// Fetches Google Fonts woff2 files and writes src/fonts.js with base64-inlined @font-face CSS.
import { writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { join, dirname } from 'path'

const CSS_URL = 'https://fonts.googleapis.com/css2?family=UnifrakturMaguntia&family=Cinzel:wght@400;600;700&family=IM+Fell+English:ital@0;1&display=swap'
const CHROME_UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'

async function fetchCss() {
  const res = await fetch(CSS_URL, { headers: { 'User-Agent': CHROME_UA } })
  if (!res.ok) throw new Error(`CSS fetch failed: ${res.status}`)
  return res.text()
}

async function fetchBase64(url) {
  const res = await fetch(url, { headers: { 'User-Agent': CHROME_UA } })
  if (!res.ok) throw new Error(`Font fetch failed: ${url} — ${res.status}`)
  const buf = await res.arrayBuffer()
  return Buffer.from(buf).toString('base64')
}

async function main() {
  console.log('Fetching Google Fonts CSS...')
  let css = await fetchCss()

  const urlPattern = /url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/g
  const urls = [...new Set([...css.matchAll(urlPattern)].map(m => m[1]))]
  console.log(`Found ${urls.length} font files`)

  for (const url of urls) {
    process.stdout.write(`  Fetching ${url.split('/').pop()}...`)
    const b64 = await fetchBase64(url)
    const ext  = url.includes('.woff2') ? 'woff2' : 'woff'
    css = css.replace(url, `data:font/${ext};base64,${b64}`)
    console.log(' done')
  }

  const out = `// Auto-generated by scripts/inline-fonts.js — do not edit manually\nexport const INLINE_FONTS = ${JSON.stringify(css)}\n`
  const outPath = join(dirname(fileURLToPath(import.meta.url)), '../src/fonts.js')
  writeFileSync(outPath, out, 'utf8')
  console.log(`\nWritten to src/fonts.js (${(out.length / 1024).toFixed(0)} KB)`)
}

main().catch(e => { console.error(e); process.exit(1) })
